/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Fire Emblem Character Schema
 */
export interface Character {
    /**
     * PouchDB required ID
     */
    _id: string;
    /**
     * Character Name
     */
    name: string;
    /**
     * URL for the character portrait, relative to src
     */
    portraitUrl: string;
    [k: string]: any;
}
