/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PouchDB required ID
 */
export type GiftId =
    | "ancient-coin"
    | "arithmetic-textbook"
    | "armored-bear-stuffy"
    | "blue-cheese"
    | "book-of-crest-designs"
    | "ceremonial-sword"
    | "exotic-spices"
    | "hunting-dagger"
    | "legends-of-chivalry"
    | "lily"
    | "smoked-meat"
    | "tasty-baked-treat"
    | "training-weight"
    | "violet";

/**
 * Fire Emblem Character Schema
 */
export interface Character {
    /**
     * PouchDB required ID
     */
    _id: string;
    /**
     * Character Name
     */
    name: string;
    /**
     * URL for the character portrait, relative to src
     */
    portraitUrl: string;
    /**
     * List of liked gifts
     */
    gifts: GiftId[];
    /**
     * Route specific information for the character
     */
    routes: any[];
}
