/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of facility
 */
export type FacilityId = "choir-practice" | "cooking-together" | "share-a-meal" | "sauna" | "advice-box";

/**
 * Fire Emblem Facility Schema
 */
export interface Facility {
    _id: FacilityId;
    /**
     * Facility Name
     */
    name: string;
    /**
     * URL for the object image, relative to src
     */
    imageUrl: string;
    configuration?: {};
}
