/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PouchDB required ID
 */
export type GiftId = "tasty-baked-treat" | "hunting-dagger";

/**
 * Fire Emblem Gift Schema
 */
export interface Gift {
    _id: GiftId;
    /**
     * Gift Name
     */
    name: string;
    /**
     * URL for the object image, relative to src
     */
    imageUrl: string;
}
