/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of gift
 */
export type GiftId =
    | "ancient-coin"
    | "arithmetic-textbook"
    | "armored-bear-stuffy"
    | "blue-cheese"
    | "book-of-crest-designs"
    | "ceremonial-sword"
    | "exotic-spices"
    | "hunting-dagger"
    | "legends-of-chivalry"
    | "lily"
    | "smoked-meat"
    | "tasty-baked-treat"
    | "training-weight"
    | "violet"
    | "whetstone"
    | "riding-boots"
    | "owl-feather"
    | "watering-can"
    | "fishing-float"
    | "floral-adornment"
    | "landscape-painting"
    | "goddess-statuette"
    | "gemstone-beads"
    | "stylish-hair-clip";

/**
 * Fire Emblem Gift Schema
 */
export interface Gift {
    _id: GiftId;
    /**
     * Gift Name
     */
    name: string;
    /**
     * URL for the object image, relative to src
     */
    imageUrl: string;
}
