/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of lost item
 */
export type LostItemId =
    | "encyclopediaOfSweets"
    | "princessDoll"
    | "newBottleOfPerfume"
    | "moonKnightsTale"
    | "evilRepellingAmulet"
    | "bundleOfHerbs"
    | "blackIronSpur"
    | "swordBeltFragment"
    | "toothedDagger"
    | "woodenButton"
    | "burlapSackOfRocks"
    | "bigSpoon";

/**
 * Fire Emblem Lost Item Schema
 */
export interface LostItems {
    _id: LostItemId;
    /**
     * Lost Item Name
     */
    name: string;
}
