/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of meal
 */
export type Meal1 = "peachSorbet" | "friedCrayfish";

/**
 * Fire Emblem Meal Schema
 */
export interface Meal {
    _id: Meal1;
    /**
     * Meal name
     */
    name: string;
}
