/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Type of merchant
 */
export type MerchantId = "eastern" | "southern" | "dark";
/**
 * Name of gift
 */
export type GiftId =
    | "ancient-coin"
    | "arithmetic-textbook"
    | "armored-bear-stuffy"
    | "blue-cheese"
    | "book-of-crest-designs"
    | "ceremonial-sword"
    | "exotic-spices"
    | "hunting-dagger"
    | "legends-of-chivalry"
    | "lily"
    | "smoked-meat"
    | "tasty-baked-treat"
    | "training-weight"
    | "violet";

/**
 * Fire Emblem Merchant Schema
 */
export interface Merchant {
    _id: MerchantId;
    /**
     * Merchant name
     */
    name: string;
    /**
     * List of items sold
     */
    wares: {
        id: GiftId;
        price: number;
    }[];
}
